11.4.customization of admins of goods
thinknetica-django-lab-02/Alone-elvi pull request #103
Opened 2021-05-05 08:49 UTC by Alone-elvi

Closes#86

2021-05-05 08:50 UTC, Alone-elvi commented
Closes#86

2021-05-05 14:38 UTC, morgangt requested changes
обновите requirements.txt и у вас есть изменение модели но нет миграций, стоит о добавление миграций в проект - это удобно

2021-05-06 10:44 UTC, morgangt approved these changes

2021-05-06 10:44 UTC, morgangt commented on thinktetika/main/models_factory.py
> +                self.tags.add(TagFactory())
через add все таки заработало 👍

2021-05-12 19:03 UTC, merged