14 3 installation and initial setup django rest framework
thinknetica-django-lab-02/Alone-elvi pull request #113
Opened 2021-05-09 17:22 UTC by Alone-elvi

Closes#98

2021-05-11 17:35 UTC, morgangt requested changes
пересмотрите сериалайзеры

2021-05-11 17:35 UTC, morgangt commented on thinktetika/main/api/serializers.py
> +        fields = "__all__"
зачем тут описывает все поля а потом в meta указывать `fields = "__all__"`
Можно не описывать все поля

2021-05-11 20:46 UTC, Alone-elvi commented on thinktetika/main/api/serializers.py
> +        fields = "__all__"
Или не указывать __all__? Какой вариант предпочтительнее? Могу узнать резоны?

2021-05-11 21:01 UTC, Alone-elvi commented
И в непроверенных осталось #115 и #116

2021-05-14 07:48 UTC, Alone-elvi commented on thinktetika/main/api/serializers.py
> +        fields = "__all__"
Да, Вы указывали на этот момент в предыдущем задании, там это исправилось.

2021-05-14 07:50 UTC, Alone-elvi commented on thinktetika/main/api/serializers.py
> +        fields = "__all__"
Сейчас гляннул данное ревью, тут тоже это момент исправлен. 
Можете принять? 
Да и ещё, как просил до этого #105, #106, #107.
Спасибо.

2021-05-16 10:27 UTC, morgangt approved these changes

2021-05-16 10:39 UTC, merged